name = "Persian Hugo"
license = "MIT"
licenselink = "https://github.com/gethugothemes/persian-hugo/blob/master/LICENSE"
description = "Persian is a Box design personal blog theme Based on Bootstrap and powered By Hugo."
homepage = "https://gethugothemes.com/products/persian-hugo/"
demosite = "https://demo.gethugothemes.com/persian/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'gethugothemes', 'typography']
features = ['bootstrap','responsive']
min_version = "0.70.0"

[author]
  name = "Gethugothemes"
  homepage = "https://gethugothemes.com/"
