######################## default configuration ####################
baseURL = "/"
title = "Persian"
theme = "persian-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
pagination.pagerSize = "5"
