baseURL = "abigailjoy.photo.netlify.com"
disqusShortname = ""
languageCode = "en-us"
languageName = "En"
paginate = "5"
theme = "persian"
title = "Abigail Joy Photography"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Info"
weight = 3
[[menu.main]]
name = "About"
url = "about"
weight = 2
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
description = "This is meta description"
logo = "images/logo.png"
search = true
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
